import {
  aprendicesPaths,
  aprendizPaths,
  asistenciaPaths,
  bienestarPaths,
  DASHBOARD_PATH,
  fichasPaths,
  infraestructuraPaths,
  administracionPaths,
  permisosPaths,
  PERFIL_PATH,
  personasPaths,
  programasPaths,
  instructoresPaths,
  vigilanciaPaths,
} from '../../routes/paths';
import type { SidebarManifestItem } from './types';

export const SIDEBAR_MANIFEST: SidebarManifestItem[] = [
  {
    section: 'Inicio',
    path: PERFIL_PATH,
    label: 'Mi perfil',
    permission: null,
    iconKey: 'perfil',
  },
  {
    section: 'Inicio',
    path: aprendizPaths.misInasistencias,
    label: 'Mis inasistencias',
    permission: null,
    rolesRequired: ['APRENDIZ'],
    alsoVisibleForPermissions: ['VER MIS INASISTENCIAS'],
    iconKey: 'asistencia/mis-inasistencias',
  },
  {
    section: 'Inicio',
    path: DASHBOARD_PATH,
    label: 'Dashboard',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'BIENESTAR AL APRENDIZ'],
    alsoVisibleForPermissions: ['VER MI AGENDA'],
    iconKey: 'dashboard',
  },
  {
    section: 'Gestión académica',
    path: programasPaths.index,
    label: 'Programas',
    permission: 'VER PROGRAMAS',
    iconKey: 'programas',
  },
  {
    section: 'Gestión académica',
    path: fichasPaths.index,
    label: 'Fichas',
    permission: 'VER FICHAS',
    alsoVisibleForRoles: ['INSTRUCTOR'],
    iconKey: 'fichas',
  },
  {
    section: 'Gestión de personal',
    path: instructoresPaths.index,
    label: 'Instructores',
    permission: 'VER FICHAS',
    iconKey: 'instructores',
  },
  {
    section: 'Gestión de personal',
    path: aprendicesPaths.index,
    label: 'Aprendices',
    permission: 'VER APRENDICES',
    iconKey: 'aprendices',
  },
  {
    section: 'Gestión de personal',
    path: personasPaths.index,
    label: 'Personas',
    permission: 'VER PERSONAS',
    iconKey: 'personas',
  },
  {
    section: 'Control y seguimiento',
    path: asistenciaPaths.fichas,
    label: 'Tomar asistencia',
    permission: 'VER ASISTENCIA',
    iconKey: 'asistencia',
  },
  {
    section: 'Control y seguimiento',
    path: asistenciaPaths.historial.index,
    label: 'Historial asistencias',
    permission: 'VER ASISTENCIA',
    iconKey: 'asistencia/historial',
  },
  {
    section: 'Control y seguimiento',
    path: asistenciaPaths.index,
    label: 'Dashboard asistencia',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'BIENESTAR AL APRENDIZ'],
    iconKey: 'asistencia/dashboard',
  },
  {
    section: 'Bienestar al aprendiz',
    path: bienestarPaths.casos.index,
    label: 'Casos Bienestar',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'BIENESTAR AL APRENDIZ'],
    iconKey: 'bienestar/casos',
  },
  {
    section: 'Control y seguimiento',
    path: asistenciaPaths.tiposObservacion,
    label: 'Tipos de observación',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR'],
    iconKey: 'asistencia/tipos-observacion',
  },
  {
    section: 'Infraestructura',
    path: infraestructuraPaths.sedes,
    label: 'Sedes',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR'],
    iconKey: 'infraestructura/sedes',
  },
  {
    section: 'Infraestructura',
    path: infraestructuraPaths.bloques,
    label: 'Bloques',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR'],
    iconKey: 'infraestructura/bloques',
  },
  {
    section: 'Infraestructura',
    path: infraestructuraPaths.pisos,
    label: 'Pisos',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR'],
    iconKey: 'infraestructura/pisos',
  },
  {
    section: 'Infraestructura',
    path: infraestructuraPaths.ambientes,
    label: 'Ambientes de formación',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR'],
    iconKey: 'infraestructura/ambientes',
  },
  {
    section: 'Control y seguimiento',
    path: vigilanciaPaths.ambientes,
    label: 'Vigilancia de ambientes',
    permission: null,
    rolesRequired: ['VIGILANTE', 'SUPER ADMINISTRADOR'],
    iconKey: 'vigilancia/ambientes',
  },
  {
    section: 'Administración',
    path: administracionPaths.jornadas,
    label: 'Jornadas de formación',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR'],
    iconKey: 'administracion/jornadas',
  },
  {
    section: 'Administración',
    path: administracionPaths.diasSinFormacion,
    label: 'Días sin formación',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR'],
    iconKey: 'administracion/dias-sin-formacion',
  },
  {
    section: 'Administración',
    path: permisosPaths.index,
    label: 'Permisos y roles',
    permission: 'ASIGNAR PERMISOS',
    iconKey: 'permisos',
  },
];
